### ISSUE TITLE
cannot run in docker

### ISSUE THREAD

**Issue by andker87** [maxill1/ialarm-mqtt#2]
once I launch the command to run via docker, this is the error I get

Found arg -c with value /config
Found external config.json /config/
error loading config.json Error: Cannot find module '/config/config.json'
Require stack:
- /usr/src/app/bin/ialarm-mqtt.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:793:17)
    at Function.Module._load (internal/modules/cjs/loader.js:686:27)
    at Module.require (internal/modules/cjs/loader.js:848:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/usr/src/app/bin/ialarm-mqtt.js:74:18)
    at Module._compile (internal/modules/cjs/loader.js:955:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:991:10)
    at Module.load (internal/modules/cjs/loader.js:811:32)
    at Function.Module._load (internal/modules/cjs/loader.js:723:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1043:10) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/usr/src/app/bin/ialarm-mqtt.js' ]
}

**Comment by maxill1** [comment]
Hi Andrea,

it seems like your container is binding the path "/config" to an empty folder or to a wrong path.

Please run the following command and check the "Binds" json property.

> docker inspect **ialarm-mqtt**

(change **ialarm-mqtt** to the name of your container)

**Comment by andker87** [comment]
still not working...
I used as path my hassio config folder, as other dockers do, but I still get an error:

`root@raspberrypi:~# docker run --name ialarm-mqtt --restart always -v /usr/share/hassio/homeassistant:/config maxill1/ialarm-mqtt:latest
Found arg -c with value /config
Found external config.json /config/
error loading config.json Error: Cannot find module '/config/config.json'
Require stack:
- /usr/src/app/bin/ialarm-mqtt.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:793:17)
    at Function.Module._load (internal/modules/cjs/loader.js:686:27)
    at Module.require (internal/modules/cjs/loader.js:848:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/usr/src/app/bin/ialarm-mqtt.js:74:18)
    at Module._compile (internal/modules/cjs/loader.js:955:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:991:10)
    at Module.load (internal/modules/cjs/loader.js:811:32)
    at Function.Module._load (internal/modules/cjs/loader.js:723:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1043:10) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/usr/src/app/bin/ialarm-mqtt.js' ]
}
`

**Comment by maxill1** [comment]
/usr/share/hassio/homeassistant contains the ialarm-mqtt config.json file?

Anyway to avoid confusion or data corruption you should not use directly the hassio config folder, make one on your host or at least you should use a subfolder of /usr/share/hassio/homeassistant.

for example, make the dir on your host:

`sudo mkdir /usr/share/hassio/homeassistant/ialarm`

download the lastest config.json from master branch:

`sudo wget https://raw.githubusercontent.com/maxill1/ialarm-mqtt/master/config.json`

edit your configuration (ip, username, mqtt, etc):

`nano /usr/share/hassio/homeassistant/ialarm/config.json`

and finally recreate the container:
> docker run --name ialarm-mqtt --restart always -v **/usr/share/hassio/homeassistant/ialarm**:/config maxill1/ialarm-mqtt:latest

**Comment by andker87** [comment]
Perfect, I managed to make it all work, apparently it was a directory permission issue, however I fixed it, thank you.
I really like the project and I have a couple of ideas for improvement to share if possible. besides the pull request here on GitHub, is there a way to send you a direct message to ask you a couple of info about this project?

**Comment by maxill1** [comment]
Any ideas or help will be appreciated. 
I don't think that GitHub has direct messages. You can find my email in the git logs ;) or i'm on [twitter](https://twitter.com/setmaat) (i'm not active but has PM).

I just merged your PR and released 0.6.2 on npm and docker.
